local function onClientResourceStart()
    -- items
    local dff = engineLoadDFF("items/backpack_british.dff")
    engineReplaceModel(dff, 1318)
    local txd = engineLoadTXD("items/backpack_british.txd")
    engineImportTXD(txd, 1318)
    local dff = engineLoadDFF("items/backpack_patrol.dff")
    engineReplaceModel(dff, 3026)
    local txd = engineLoadTXD("items/backpack_patrol.txd")
    engineImportTXD(txd, 3026)

    -- skin skins
    local dff = engineLoadDFF("skins/male01.dff")
    engineReplaceModel(dff, 7)
    local txd = engineLoadTXD("skins/male01.txd")
    engineImportTXD(txd, 7)
    local dff = engineLoadDFF("skins/ofost.dff")
    engineReplaceModel(dff, 54)
    local txd = engineLoadTXD("skins/ofost.txd")
    engineImportTXD(txd, 54)
    local dff = engineLoadDFF("skins/hmori.dff")
    engineReplaceModel(dff, 43)
    local txd = engineLoadTXD("skins/hmori.txd")
    engineImportTXD(txd, 43)
    local dff = engineLoadDFF("skins/zero.dff")
    engineReplaceModel(dff, 306)
    local txd = engineLoadTXD("skins/zero.txd")
    engineImportTXD(txd, 306)
    local dff = engineLoadDFF("skins/vwmotr1.dff")
    engineReplaceModel(dff, 212)
    local txd = engineLoadTXD("skins/vwmotr1.txd")
    engineImportTXD(txd, 212)

    -- clothes skins
    local dff = engineLoadDFF("clothes/boxingcap.dff")
    engineReplaceModel(dff, 30017)
    local txd = engineLoadTXD("clothes/boxingcap.txd")
    engineImportTXD(txd, 30260)
    local dff = engineLoadDFF("clothes/hockeymask.dff")
    engineReplaceModel(dff, 30091)
    local txd = engineLoadTXD("clothes/hockey.txd")
    engineImportTXD(txd, 30376)

    -- weapons skins
    -- parachute
    -- local dff = engineLoadDFF("weapons/gun_para.dff")
    -- engineReplaceModel(dff, 371)
    -- local txd = engineLoadTXD("weapons/gun_para.txd")
    -- engineImportTXD(txd, 371)
    -- desert eagle
    local dff = engineLoadDFF("weapons/desert_eagle.dff")
    engineReplaceModel(dff, 348)
    local txd = engineLoadTXD("weapons/desert_eagle.txd")
    engineImportTXD(txd, 348)
    -- ak47
    local dff = engineLoadDFF("weapons/ak47.dff")
    engineReplaceModel(dff, 355)
    local txd = engineLoadTXD("weapons/ak47.txd")
    engineImportTXD(txd, 355)
    -- m4
    local dff = engineLoadDFF("weapons/m4.dff")
    engineReplaceModel(dff, 356)
    local txd = engineLoadTXD("weapons/m4.txd")
    engineImportTXD(txd, 356)
    -- rifle
    local dff = engineLoadDFF("weapons/rifle.dff")
    engineReplaceModel(dff, 357)
    local txd = engineLoadTXD("weapons/rifle.txd")
    engineImportTXD(txd, 357)
    -- sniper
    local dff = engineLoadDFF("weapons/sniper.dff")
    engineReplaceModel(dff, 358)
    local txd = engineLoadTXD("weapons/sniper.txd")
    engineImportTXD(txd, 358)
    -- shotgun
    local dff = engineLoadDFF("weapons/shotgun.dff")
    engineReplaceModel(dff, 349)
    local txd = engineLoadTXD("weapons/shotgun.txd")
    engineImportTXD(txd, 349)

    -- vehicle skins
    local dff = engineLoadDFF("vehicles/buffalo.dff")
    engineReplaceModel(dff, 402)
    local txd = engineLoadTXD("vehicles/buffalo.txd")
    engineImportTXD(txd, 402)
    local dff = engineLoadDFF("vehicles/alpha.dff")
    engineReplaceModel(dff, 602)
    local txd = engineLoadTXD("vehicles/alpha.txd")
    engineImportTXD(txd, 602)
    local dff = engineLoadDFF("vehicles/bullet.dff")
    engineReplaceModel(dff, 541)
    local txd = engineLoadTXD("vehicles/bullet.txd")
    engineImportTXD(txd, 541)
    local dff = engineLoadDFF("vehicles/merit.dff")
    engineReplaceModel(dff, 551)
    local txd = engineLoadTXD("vehicles/merit.txd")
    engineImportTXD(txd, 551)
    local dff = engineLoadDFF("vehicles/jester_2.dff")
    engineReplaceModel(dff, 559)
    local txd = engineLoadTXD("vehicles/jester_2.txd")
    engineImportTXD(txd, 559)
    local dff = engineLoadDFF("vehicles/zr-350.dff")
    engineReplaceModel(dff, 477)
    local txd = engineLoadTXD("vehicles/zr-350.txd")
    engineImportTXD(txd, 477)
    local dff = engineLoadDFF("vehicles/euros.dff")
    engineReplaceModel(dff, 587)
    local txd = engineLoadTXD("vehicles/euros.txd")
    engineImportTXD(txd, 587)
    local dff = engineLoadDFF("vehicles/infernus.dff")
    engineReplaceModel(dff, 411)
    local txd = engineLoadTXD("vehicles/infernus.txd")
    engineImportTXD(txd, 411)
    local dff = engineLoadDFF("vehicles/turismo.dff")
    engineReplaceModel(dff, 451)
    local txd = engineLoadTXD("vehicles/turismo.txd")
    engineImportTXD(txd, 451)
    local dff = engineLoadDFF("vehicles/willard.dff")
    engineReplaceModel(dff, 529)
    local txd = engineLoadTXD("vehicles/willard.txd")
    engineImportTXD(txd, 529)
    local dff = engineLoadDFF("vehicles/stallion.dff")
    engineReplaceModel(dff, 439)
    local txd = engineLoadTXD("vehicles/stallion.txd")
    engineImportTXD(txd, 439)
    local dff = engineLoadDFF("vehicles/bravura.dff")
    engineReplaceModel(dff, 401)
    local txd = engineLoadTXD("vehicles/bravura.txd")
    engineImportTXD(txd, 401)
    local dff = engineLoadDFF("vehicles/flash.dff")
    engineReplaceModel(dff, 565)
    local txd = engineLoadTXD("vehicles/flash.txd")
    engineImportTXD(txd, 565)
    local dff = engineLoadDFF("vehicles/fcr-900.dff")
    engineReplaceModel(dff, 521)
    local txd = engineLoadTXD("vehicles/fcr-900.txd")
    engineImportTXD(txd, 521)
    local dff = engineLoadDFF("vehicles/tahoma.dff") -- bad
    engineReplaceModel(dff, 566)
    local txd = engineLoadTXD("vehicles/tahoma.txd")  -- bad
    engineImportTXD(txd, 566)
    local dff = engineLoadDFF("vehicles/cheetah.dff")
    engineReplaceModel(dff, 415)
    local txd = engineLoadTXD("vehicles/cheetah.txd")
    engineImportTXD(txd, 415)
    local dff = engineLoadDFF("vehicles/hotring_racer_3.dff")
    engineReplaceModel(dff, 502)
    local txd = engineLoadTXD("vehicles/hotring_racer_3.txd")
    engineImportTXD(txd, 502)
    local dff = engineLoadDFF("vehicles/taxi.dff")
    engineReplaceModel(dff, 420)
    local txd = engineLoadTXD("vehicles/taxi.txd")
    engineImportTXD(txd, 420)
    local dff = engineLoadDFF("vehicles/emperor.dff")
    engineReplaceModel(dff, 585)
    local txd = engineLoadTXD("vehicles/emperor.txd")
    engineImportTXD(txd, 585)
    local dff = engineLoadDFF("vehicles/bobcat.dff")
    engineReplaceModel(dff, 422)
    local txd = engineLoadTXD("vehicles/bobcat.txd")
    engineImportTXD(txd, 422)
    local dff = engineLoadDFF("vehicles/police_ls.dff")
    engineReplaceModel(dff, 596)
    local txd = engineLoadTXD("vehicles/police_ls.txd")
    engineImportTXD(txd, 596)
    local dff = engineLoadDFF("vehicles/admiral.dff")
    engineReplaceModel(dff, 445)
    local txd = engineLoadTXD("vehicles/admiral.txd")
    engineImportTXD(txd, 445)
    local dff = engineLoadDFF("vehicles/elegy.dff")
    engineReplaceModel(dff, 562)
    local txd = engineLoadTXD("vehicles/elegy.txd")
    engineImportTXD(txd, 562)
    local dff = engineLoadDFF("vehicles/super_gt.dff")
    engineReplaceModel(dff, 506)
    local txd = engineLoadTXD("vehicles/super_gt.txd")
    engineImportTXD(txd, 506)
    local dff = engineLoadDFF("vehicles/sultan.dff")
    engineReplaceModel(dff, 560)
    local txd = engineLoadTXD("vehicles/sultan.txd")
    engineImportTXD(txd, 560)
    local dff = engineLoadDFF("vehicles/premier.dff")
    engineReplaceModel(dff, 426)
    local txd = engineLoadTXD("vehicles/premier.txd")
    engineImportTXD(txd, 426)
    local dff = engineLoadDFF("vehicles/primo.dff")
    engineReplaceModel(dff, 547)
    local txd = engineLoadTXD("vehicles/primo.txd")
    engineImportTXD(txd, 547)
    local dff = engineLoadDFF("vehicles/sentinel.dff")
    engineReplaceModel(dff, 405)
    local txd = engineLoadTXD("vehicles/sentinel.txd")
    engineImportTXD(txd, 405)
    local dff = engineLoadDFF("vehicles/solair.dff")
    engineReplaceModel(dff, 458)
    local txd = engineLoadTXD("vehicles/solair.txd")
    engineImportTXD(txd, 458)
    local dff = engineLoadDFF("vehicles/freeway.dff")
    engineReplaceModel(dff, 463)
    local txd = engineLoadTXD("vehicles/freeway.txd")
    engineImportTXD(txd, 463)
end

-- Event Handlers

addEventHandler("onClientResourceStart", getRootElement(), onClientResourceStart)
